#!/usr/bin/env bash

set -euo pipefail

PGPACKAGE_VERSION="${1}"
TAP_TEMPLATE_FILE="$(realpath "${2}")"
PGPACKAGE_GH_REPO="${PGPACKAGE_GH_REPO:-MagnusOpera/pgpackage}"

export PGPACKAGE_VERSION

cd "$(mktemp -d)"

>&2 echo "::info Generating Homebrew formula for pgpackage ${PGPACKAGE_VERSION}"
>&2 echo "::group::Download release assets"
>&2 gh release download --repo "${PGPACKAGE_GH_REPO}" "${PGPACKAGE_VERSION}" \
  -p "pgpackage-${PGPACKAGE_VERSION}-darwin-x64.zip" \
  -p "pgpackage-${PGPACKAGE_VERSION}-darwin-arm64.zip" \
  -p "pgpackage-${PGPACKAGE_VERSION}-linux-x64.zip" \
  -p "pgpackage-${PGPACKAGE_VERSION}-linux-arm64.zip" \
  --skip-existing
>&2 echo "::endgroup::"

for i in \
  "darwin x64   PGPACKAGE_DARWIN_X64" \
  "darwin arm64 PGPACKAGE_DARWIN_ARM64" \
  "linux x64    PGPACKAGE_LINUX_X64" \
  "linux arm64  PGPACKAGE_LINUX_ARM64" \
  ; do
  # shellcheck disable=SC2086
  set -- $i
  OS="$1"
  ARCH="$2"
  ENV_VAR="$3"
  ASSET="pgpackage-${PGPACKAGE_VERSION}-${OS}-${ARCH}.zip"
  SHA256="$(sha256sum "$ASSET" | cut -f1 -d' ')"

  SHA256_VAR="${ENV_VAR}_SHA256"
  URL_VAR="${ENV_VAR}_URL"
  printf -v "${SHA256_VAR}" "%s" "${SHA256}"
  printf -v "${URL_VAR}" "%s" "https://github.com/${PGPACKAGE_GH_REPO}/releases/download/${PGPACKAGE_VERSION}/${ASSET}"

  export "${SHA256_VAR?}"
  export "${URL_VAR?}"
  >&2 echo "${OS}-${ARCH} SHA256: ${!SHA256_VAR}"
  >&2 echo "${OS}-${ARCH} URL:    ${!URL_VAR}"
done

envsubst '$PGPACKAGE_VERSION,$PGPACKAGE_DARWIN_X64_URL,$PGPACKAGE_DARWIN_X64_SHA256,$PGPACKAGE_DARWIN_ARM64_URL,$PGPACKAGE_DARWIN_ARM64_SHA256,$PGPACKAGE_LINUX_X64_URL,$PGPACKAGE_LINUX_X64_SHA256,$PGPACKAGE_LINUX_ARM64_URL,$PGPACKAGE_LINUX_ARM64_SHA256' < "${TAP_TEMPLATE_FILE}"
