# This file was generated by https://github.com/MagnusOpera/pgpackage/blob/main/.github/scripts/generate-homebrew-tap
class Pgpackage < Formula
  desc "Go-first PostgreSQL schema packaging CLI"
  homepage "https://github.com/MagnusOpera/pgpackage"
  version "${PGPACKAGE_VERSION}"

  if OS.mac? && Hardware::CPU.intel?
    url "${PGPACKAGE_DARWIN_X64_URL}"
    sha256 "${PGPACKAGE_DARWIN_X64_SHA256}"
  end

  if OS.mac? && Hardware::CPU.arm?
    url "${PGPACKAGE_DARWIN_ARM64_URL}"
    sha256 "${PGPACKAGE_DARWIN_ARM64_SHA256}"
  end

  if OS.linux? && Hardware::CPU.intel?
    url "${PGPACKAGE_LINUX_X64_URL}"
    sha256 "${PGPACKAGE_LINUX_X64_SHA256}"
  end

  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "${PGPACKAGE_LINUX_ARM64_URL}"
    sha256 "${PGPACKAGE_LINUX_ARM64_SHA256}"
  end

  def install
    bin.install "pgpackage"
  end

  test do
    system bin/"pgpackage", "--version"
  end
end
